# Generated by Django 5.2.17 on 2026-09-28 23:40

import django.db.models.deletion
import transporte.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('total_asientos', models.PositiveIntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('piso', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(choices=[('SEMICAMA', 'Semicama'), ('CAMA', 'Cama Premium')], default='SEMICAMA', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='transporte.bus')),
            ],
            options={
                'unique_together': {('bus', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='CarroPasajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('PASAJERO', 'Pasajero'), ('ADMIN_FLOTA', 'Administrador de Flota')], default='PASAJERO', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField()),
                ('precio_base', models.PositiveIntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='transporte.bus')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_destino', to='transporte.ciudad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_origen', to='transporte.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ocupante', models.CharField(max_length=150)),
                ('rut_ocupante', models.CharField(max_length=12, validators=[transporte.models.validar_rut_chileno])),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.asiento')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transporte.carropasajes')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.servicio')),
            ],
            options={
                'unique_together': {('carro', 'servicio', 'asiento')},
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pasajero', models.CharField(max_length=150)),
                ('rut_pasajero', models.CharField(max_length=12, validators=[transporte.models.validar_rut_chileno])),
                ('precio_pagado', models.PositiveIntegerField()),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.asiento')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='transporte.servicio')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='transporte.venta')),
            ],
            options={
                'unique_together': {('servicio', 'asiento', 'venta')},
            },
        ),
    ]
