# Generated by Django 5.2.17 on 2026-09-29 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='fecha',
            new_name='fecha_venta',
        ),
        migrations.RemoveField(
            model_name='asiento',
            name='piso',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='total_asientos',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='region',
        ),
        migrations.AddField(
            model_name='carropasajes',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='agregado_en',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='tipo',
            field=models.CharField(choices=[('SEMICAMA', 'Semicama'), ('SALON_CAMA', 'Salón Cama')], default='SEMICAMA', max_length=20),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='transporte.asiento'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='rut_pasajero',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='transporte.servicio'),
        ),
        migrations.AlterField(
            model_name='itemcarro',
            name='rut_ocupante',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='transporte.bus'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llegadas', to='transporte.ciudad'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='transporte.ciudad'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
    ]
