# Generated by Django 5.2.17 on 2026-09-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_rename_user_perfilusuario_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ENTREGADO', 'Entregado / Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
