# Generated by Django 5.2.17 on 2026-09-30 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_alter_venta_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asiento',
            options={'ordering': ['numero'], 'verbose_name': 'Asiento', 'verbose_name_plural': 'Asientos'},
        ),
        migrations.AlterModelOptions(
            name='boleto',
            options={'verbose_name': 'Boleto', 'verbose_name_plural': 'Boletos'},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='carropasajes',
            options={'verbose_name': 'Carro de Pasajes', 'verbose_name_plural': 'Carros de Pasajes'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['nombre'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='itemcarro',
            options={'verbose_name': 'Ítem de Carro', 'verbose_name_plural': 'Ítems de Carro'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['fecha_salida'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_venta'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterField(
            model_name='asiento',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='transporte.bus', verbose_name='Bus Asignado'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Número de Butaca'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='tipo',
            field=models.CharField(choices=[('SEMICAMA', 'Semicama'), ('SALON_CAMA', 'Salón Cama')], default='SEMICAMA', max_length=20, verbose_name='Tipo de Asiento'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.asiento', verbose_name='Asiento Asignado'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='nombre_pasajero',
            field=models.CharField(max_length=150, verbose_name='Nombre del Pasajero'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='precio_pagado',
            field=models.PositiveIntegerField(verbose_name='Precio Pagado'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='rut_pasajero',
            field=models.CharField(max_length=12, verbose_name='RUT del Pasajero'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos_emitidos', to='transporte.servicio', verbose_name='Servicio de Transporte'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='transporte.venta', verbose_name='Venta Asociada'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='patente',
            field=models.CharField(max_length=10, unique=True, verbose_name='Patente Vehicular'),
        ),
        migrations.AlterField(
            model_name='carropasajes',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='carropasajes',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='carropasajes',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro_pasajes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Ciudad'),
        ),
        migrations.AlterField(
            model_name='itemcarro',
            name='agregado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inclusión'),
        ),
        migrations.AlterField(
            model_name='itemcarro',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.asiento', verbose_name='Butaca Seleccionada'),
        ),
        migrations.AlterField(
            model_name='itemcarro',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transporte.carropasajes', verbose_name='Carro Contenedor'),
        ),
        migrations.AlterField(
            model_name='itemcarro',
            name='nombre_ocupante',
            field=models.CharField(max_length=150, verbose_name='Nombre del Ocupante'),
        ),
        migrations.AlterField(
            model_name='itemcarro',
            name='rut_ocupante',
            field=models.CharField(max_length=12, verbose_name='RUT del Ocupante'),
        ),
        migrations.AlterField(
            model_name='itemcarro',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carros', to='transporte.servicio', verbose_name='Servicio Programado'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN_FLOTA', 'Administrador de Flota'), ('PASAJERO', 'Pasajero Cliente')], default='PASAJERO', max_length=20, verbose_name='Rol en la Plataforma'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='transporte.bus', verbose_name='Bus Asignado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_destino', to='transporte.ciudad', verbose_name='Ciudad de Destino'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_salida',
            field=models.DateTimeField(verbose_name='Fecha y Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_origen', to='transporte.ciudad', verbose_name='Ciudad de Origen'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio_base',
            field=models.PositiveIntegerField(verbose_name='Precio Base (Semicama)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Orden'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.PositiveIntegerField(verbose_name='Total de la Transacción'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente Comprador'),
        ),
    ]
